### ISSUE TITLE
asynchronously implement the training and prediction process？

### ISSUE THREAD

**Issue by leepand** [fidelity/mabwiser#23]
Very nice project, but how to asynchronously implement the training and prediction process

**Comment by erstrong** [comment]
Hi @leepand,

Thank you for your interest in using MABWiser! Could you provide more detail about your request?

**Comment by leepand** [comment]
@erstrong  Thank you for that quick response. In a production environment, we often need to separate model updates from predictions for system  performance, i.e. one api gets user feedback and updates the model, while the other api uses the latest model information for predictions.

**Comment by erstrong** [comment]
Hi @leepand,
The library is designed for prototyping and simulations. You can of course use it in any way you want under the Apache 2.0 license, but we have not tested it for production use or asynchronous programming.

Regarding your specific question, predict would be blocked by the fit method as it requires that the fit method must have been previously called on at least one row of data. After that initial fit, there is nothing in the API to prevent partial fit and predict from running concurrently. However, some of the learning policies both update stored attributes in fit/partial fit and perform calculations with those attributes in predict, which could create problems. 

If you want to use the library in a live environment, I would suggest fitting the model offline or scheduling partial fitting to occur during recurring downtime. The MAB objects can be serialized with the pickle protocol. You might also want to look at [StreamingBandit](https://github.com/Nth-iteration-labs/streamingbandit) which is designed for live experiments.

**Comment by leepand** [comment]
Hi @erstrong,
Thank you so much for your response, I'll try the pickle method.
