### ISSUE TITLE
Using categorical variables in the context

### ISSUE THREAD

**Issue by ayush488** [fidelity/mabwiser#29]
Do I need to convert the categorical variables using one-hot encoding in order to use in the context. Does the context only use numerical features or can it accept categorical features as well?

**Comment by erstrong** [comment]
Hi @ayush488,

Thank you for your interest in using MABWiser! For context features, the supported data types are integer, float and boolean. If you have other data types for some of your features you will need to perform pre-processing to convert those features to one of the supported data types.

**Comment by ayush488** [comment]
Thanks.
