### ISSUE TITLE
init order

### ISSUE THREAD

**Issue by ggsonic** [fidelity/mabwiser#30]
in class _Linear ,__init__, with order `l2_lambda ,alpha`
but in customized_mab.py, class LinUCBColdStart(_Linear) __init__ with order `alpha, l2_lambda`,
is this correct?

**Comment by bkleyn** [comment]
Thank you for your interest in the library and for reaching out. No, this does look like a bug in the `LinUCBColdStart` class. Specifically `alpha` and `l2_lambda` should be switched around when `_Linear` is initialized.

**Comment by bkleyn** [comment]
I created a [pull request](https://github.com/fidelity/mabwiser/pull/31) to resolve this.
