### ISSUE TITLE
number of arms

### ISSUE THREAD

**Issue by Harricane-data** [fidelity/mabwiser#40]
Hi Mabwiser team,
Thank you so much for the great work on the MAB library with neighborhood policy. I really loved it.
I am using mabwiser for recommendation systems, but my number of arms can be in thousands. The library works fine when we have arms in a few hundred, but looking into various ways to do better recommendations using mabwiser. Is there any limit or max number of arms without sacrificing the performance? Thank you in advance.

**Comment by skadio** [comment]
Hi @Harricane-data, 

Thank you for the positive feedback --glad you find it is useful in your applications!

Aside from the mabwiser implementation, it is a valid question in Bandits literature on how to treat cases with a large (1000+) number of arms. The ultimate goal is to learn an unknown distribution of reward for each arm, and when there exist a large number of arms --the experimentation time for learning increases. This is not desirable. 

So your point is relevant not only about runtime performance but in general. 

As for runtime efficiency: you might consider parallelization settings. See the n_jbos parameter. More broadly, you can consider Hierarchial Bandits. For instance, group 1000 content into 10 topics first, and create 2 layers of bandits to first learn a relevant topic and then to learn a particular content in that topic. With MABWiser, it should be easy to build such hierarchical bandit applications. 

Hope this helps!

**Comment by Harricane-data** [comment]
@skadio  Thank you for quick response. I will try that and get back to you if i have further questions.
