### ISSUE TITLE
How to use Categorical variables as context?

### ISSUE THREAD

**Issue by aveshadt** [fidelity/mabwiser#58]
Hi team, 
I am working on Contextual MAB, and though the example mentions "subscriber" as 0,1. But I was curious to know if I could use a different categorical variable, lets say with categories=10, so, so 9 additional dummy columns would be made. Will this impact the learning, or it can handle?

Thanks

**Comment by skadio** [comment]
As you mentioned, for Contextual MAB you need numerical input. For categorical variables, one-hot dummy encoding should work. 

A few things to watch out for would be data sparsity (lack of training samples for categories) and if you are using a non-parametric neighborhood policy, the distance metric to calculate similarity between the samples might need attention.
