### ISSUE TITLE
[Question] A way to only predict arms from a given subset?

### ISSUE THREAD

**Issue by AndriiG13** [fidelity/mabwiser#74]
We are using `mabwiser` for a production use case and have had a really good experience with the package so far!

In our use case, it's possible that at serve time, the set of available arms is a subset of all the arms that the model was trained on. So let's say we train the model on arms `[1, 2, 3]` but when we run predictions online, we can only show arms `[1, 2]`. Note, the set of available arms is known at serve time. 

I'm looking for the best way to make sure that the model only returns one of `[1, 2]`.

I've come up with a way in which I:
* call `predict_expectations()` 
* filter the expectations to keep just the available arms
* return the arm with the highest expectation 

Show in code below:
```python
from mabwiser.mab import LearningPolicy,MAB

# TRAIN TIME
mab = MAB(
    arms=[1, 2, 3],
    learning_policy=LearningPolicy.EpsilonGreedy())

mab.fit(decisions=[1, 1, 2, 2, 3, 3], rewards=[.2, .3, .4, .2, .5, .6])

# SERVE TIME
available_arms = {1, 2}

model_arms = set(mab.arms)
print(model_arms)
# {1, 2, 3}

arms_to_remove = model_arms.difference(available_arms)
print(arms_to_remove)
# {3}

# remove arms from predicted expectations and get argmax
predicted_expectations = mab.predict_expectations()
for arm in arms_to_remove:
    predicted_expectations.pop(arm)

prediction = max(predicted_expectations, key=predicted_expectations.get)
print(prediction)
# 2
```

I was really curious if you thought this was appropriate or had other suggestions. I can already see that with this approach I will have to adjust the code when I start using one of the `linear` learning policies.

I also tried a different approach where I deep copy the mab model and call `remove_arms`. But this led to buggy results, where the same strategy is always returned. I suspect this is because of taking a deep copy of the model each time before I call `predict`.

Thanks a lot!

**Comment by skadio** [comment]
Thank you for sharing your positive feedback -- glad to hear MABWiser found another production use case! 

Your scenario is very valid so we can totally relate to differences in trained arms vs. test arms. Your solution looks in the right direction to me, plus one comment: 

IF you are using MABWiser for a "recommendation" setting, I would like to bring our Mab2Rec Library https://github.com/fidelity/mab2rec to your attention. 

Mab2Rec is specifically built for personalization / recommendation applications, and uses MABWiser under the hood as the recommendation model/policy. 

Mab2Rec offers a rich API that might come in handy for Recommendation scenarios. The simplest example is top-k recommendations, to run not just one arm but multiple arms. 

```
# Import 
from mab2rec import BanditRecommender, LearningPolicy
from mab2rec.pipeline import train, score

# LinGreedy recommender to select top-4 items with 10% random exploration 
rec = BanditRecommender(LearningPolicy.LinGreedy(epsilon=0.1), top_k=4)

# Train on (user, item, response) interactions in train data using user features 
train(rec, data='data/data_train.csv', 
      user_features='data/features_user.csv')

# Score recommendations for users in test data. The output df holds 
# user_id, item_id, score columns for every test user for top-k items 
df = score(rec, data='data/data_test.csv', 
           user_features='data/features_user.csv')
```

Your scenario of "excluded_arms" is also covered!  

See the Advanced notebook here, https://github.com/fidelity/mab2rec/blob/main/notebooks/5_advanced.ipynb that talks about excluded arms, quick copy here

```
# Excluded arms for each individual user/context
excluded_arms = [['Item1'], ['Item3']]

# Generate top-k recommendation for each context
rec.recommend([[1, 1, 0], [1, 1, 1], [1, 0, 1]], excluded_arms=excluded_arms)
```

If you are not using MABWiser for recommendation scenario, you can take a look at the excluded_arm implementation that might serve as a reference for you.

Hope this helps, and please consider giving our MABWiser and Mab2Rec libraries a star to spread the word 🌟 🙏

Thanks,
Serdar

**Comment by AndriiG13** [comment]
Thank you for your reply Serdar! We are not using it for recommendations yet, so I will check out the implementation of `excluded_arms`!
