### ISSUE TITLE
Save the state of Contextual MAB

### ISSUE THREAD

**Issue by maypink** [fidelity/mabwiser#85]
Hi!

We're using your implementation of MAB in our project and it's a great pleasure! However, I'd like to ask: is there a possibility to save the current state of MAB at any time? For example, it would be useful to plot actions probabilities for different contexts throughout the evolution process in our case.

Thank you in advance!

**Comment by bkleyn** [comment]
Hey @maypink, thank you for the kind feedback. Remember to ⭐️ the library if you like it.

Based on the information you provided, one option might be to use the [predict_expectation()](https://fidelity.github.io/mabwiser/api.html#mabwiser.mab.MAB.predict_expectations) method to store the predicted expectations for each arm at different points in time. 

Alternatively, if you don't know exactly what information you need, you could serialize the MAB object by using the Python pickle library and save this for later use.

Hope this helps!

**Comment by maypink** [comment]
Thank you for reply! 

I forgot to clarify that I want to save Contextual bandits, so it's improtant to save the whole object as it is. `[predict_expectation()](https://fidelity.github.io/mabwiser/api.html#mabwiser.mab.MAB.predict_expectations)` is not enough for me in that case. Also, saving with json is much faster and compact than with pickle, so is it possible that `save` and `load` methods will be implemented in mabwiser?

**Comment by bkleyn** [comment]
Hey @maypink 

We currently don't have plans to implement dedicated `save` and `load` methods. As mentioned in the previous comment using pickle (or similar) to serialize the MAB object itself would be our suggested approach as this ensures all the variables corresponding to the bandit state is captured.
