### ISSUE TITLE
Consistently get the actual expected value for each arm

### ISSUE THREAD

**Issue by maurorb** [fidelity/mabwiser#86]
Hello, everyone!

First of all, congratulations (and thank you!) for putting this amount of work in a package that is not only easy to use, but also extremely efficient. This here is probably what will make MAB more popular in the next few years.

I would like to ask whether it is possible for the user to consistently get the expected revenues for each arm before each ˋpartial_fitˋ, with the EpsilonGreedy policy. Using ˋ.predict_expectationsˋ does not solve this entirely, since epsilon% of the predictions are going to be random.

I understand that the ultimate purpose behind ˋpredict_expectationsˋ is to work like ˋpredict_probaˋ in case we really need those expectations. But I would like to plot the *actual* expected value the bandit is storing.

I couldn't find any method to retrieve this information in the official, and I apologize in advance if the instruction is there and I didn't find.

Thank you!!

**Comment by bkleyn** [comment]
Hey @maurorb,

Thank you for your kind words and feedback.

If you are simply interested in the expected value of each arm, without any stochastic component, you can make use of the `arm_to_expectation` variable for the given MAB. 

For EpsilonGreedy you can access it as follows:

```
greedy = MAB(arms=[1, 2],
             learning_policy=LearningPolicy.EpsilonGreedy(epsilon=0.15),
             seed=123456)
arm_to_expectation = greedy._imp.arm_to_expectation
```

Hope this helps.

**Comment by aberges-grd** [comment]
I'd like to comment on this issue:

1. It feels extremely hacky to have to get into the private fields to retrieve this.
2. This method breaks when using nonparametric contextual bandits.

This all stems from the implementation using rng when predicting expectations. So the question is: why was there a need to implement it like this? The rng part should only apply when predicting arms, not rewards.
