### ISSUE TITLE
Parallel fit/predict for contextual policies

### ISSUE THREAD

**Issue by risufaj** [fidelity/mabwiser#87]
In [MAB.py line 876](https://github.com/fidelity/mabwiser/blob/881d0e9f8f70948e03daa7f2e5d8163141b727a2/mabwiser/mab.py#L876)
There is a comment that says to not use parallel fit or predict for contextual policies, but it's not clear why that needs to be the case? 

Any help would be appreciated.

**Comment by bkleyn** [comment]
Hi @risufaj 

Very keen observation. All of the contextual policies have implementations that benefit from multi-core processing. As such we do not also parallelize across arms (for fit) or contexts (for predict) as that could actually slow down performance.
